### ISSUE TITLE
welche ISO Codes?

### ISSUE THREAD

**Issue by mro** [juliuste/match-country-german#1]
die für Länder sind Großbuchstaben, z.B. http://www.lexvo.org/id/iso3166/DE. Kleinbuchstaben sind z.B. Sprachen http://www.lexvo.org/id/iso639-1/de. Oder TLDs. Vermischen macht Datenmatsch.

**Comment by juliuste** [comment]
Currently, the module usually returns the TLD (mostly ISO 3166, with slight differences like `UK` instead of `GB`). You're right, I should fix this, will do so in the next few days.

**Comment by derhuerst** [comment]
bump.

**Comment by juliuste** [comment]
I updated the dataset to [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1), including upper case country codes.

**Comment by derhuerst** [comment]
see b4b248cafdc970150a566a7de5230c549bab4df0
